import getDb from './index.js';

const products = [
    // --- MODS ---
    {
        name: 'VaporMax Elite Pro Mod - Carbon Fiber Edition',
        brand: 'TitanVape',
        flavor: 'N/A (Hardware)',
        nicotine: 'N/A',
        price: 149.99,
        rating: 4.9,
        reviews: 2450,
        image: '/images/devices/geekvape-aegis-legend.jpg',
        category: 'Mods',
        description: 'The ultimate power for professional vapers. Dual-21700 battery configuration and the advanced Titan-X chipset with OLED display.',
        stock_qty: 45,
        is_express_delivery: 1,
        is_bestseller: 1,
        is_new_arrival: 0,
    },
    {
        name: 'GeekVape Aegis Legend 2 200W',
        brand: 'GeekVape',
        flavor: 'N/A (Hardware)',
        nicotine: 'N/A',
        price: 79.99,
        rating: 4.8,
        reviews: 3820,
        image: '/images/devices/geekvape-aegis-legend.jpg',
        category: 'Mods',
        description: 'IP68 waterproof, dustproof, and shockproof. The most rugged mod for everyday carry.',
        stock_qty: 30,
        is_express_delivery: 1,
        is_bestseller: 1,
        is_new_arrival: 0,
    },
    // --- DISPOSABLES ---
    {
        name: 'Geek Bar Pulse X 25000 Puffs - Clear',
        brand: 'Geek Bar',
        flavor: 'Clear',
        nicotine: '5%',
        price: 24.50,
        rating: 4.6,
        reviews: 5102,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'The longest lasting disposable with a built-in LED screen for e-liquid and battery monitoring.',
        stock_qty: 200,
        is_express_delivery: 1,
        is_bestseller: 1,
        is_new_arrival: 0,
    },
    {
        name: 'Elf Bar BC5000 - Strawberry Mango',
        brand: 'Elf Bar',
        flavor: 'Strawberry Mango',
        nicotine: '5%',
        price: 18.99,
        rating: 4.7,
        reviews: 8930,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'The classic Elf Bar with a tropical twist — 5000 puffs, rechargeable, and iconic flavor.',
        stock_qty: 300,
        is_express_delivery: 1,
        is_bestseller: 1,
        is_new_arrival: 0,
    },
    {
        name: 'Lost Mary OS5000 - Blue Cotton Candy',
        brand: 'Lost Mary',
        flavor: 'Blue Cotton Candy',
        nicotine: '5%',
        price: 19.99,
        rating: 4.8,
        reviews: 4215,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Sweet, airy cotton candy clouds with a smooth 5% nicotine hit. 5000 puffs guaranteed.',
        stock_qty: 150,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    // --- E-LIQUIDS ---
    {
        name: 'Arctic Breeze Menthol - Sub-Ohm 60ml',
        brand: 'FrostBite',
        flavor: 'Pure Menthol & Peppermint',
        nicotine: '0mg, 3mg, 6mg',
        price: 19.50,
        rating: 4.7,
        reviews: 945,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'E-Liquids',
        description: 'The cleanest, coldest menthol on the market. Perfect for cloud chasing.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 0,
    },
    {
        name: 'Strawberry Dream Salt Nic - Premium Series 30ml',
        brand: 'SweetCloud',
        flavor: 'Strawberry Cream & Custard',
        nicotine: '25mg, 50mg',
        price: 22.99,
        rating: 4.5,
        reviews: 1820,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nic Salts',
        description: 'A smooth, creamy strawberry experience perfectly balanced for high-nicotine pod systems.',
        stock_qty: 120,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 0,
    },
    {
        name: 'Mango Tango Tropical Blend 100ml',
        brand: 'Tropika Vapes',
        flavor: 'Mango, Pineapple & Passionfruit',
        nicotine: '0mg, 3mg',
        price: 27.99,
        rating: 4.6,
        reviews: 2310,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'E-Liquids',
        description: 'A vacation in a bottle. Pure tropical escape with sweet mango and tangy pineapple.',
        stock_qty: 90,
        is_express_delivery: 0,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    // --- POD SYSTEMS ---
    {
        name: 'Uwell Caliburn G2 Pod System',
        brand: 'Uwell',
        flavor: 'N/A (Hardware)',
        nicotine: 'N/A',
        price: 39.99,
        rating: 4.9,
        reviews: 6750,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Industry-leading flavor in a slim, pocket-friendly design. The G2 sets the standard.',
        stock_qty: 60,
        is_express_delivery: 1,
        is_bestseller: 1,
        is_new_arrival: 0,
    },
    {
        name: 'Vaporesso XROS 3 Mini',
        brand: 'Vaporesso',
        flavor: 'N/A (Hardware)',
        nicotine: 'N/A',
        price: 34.99,
        rating: 4.7,
        reviews: 3100,
        image: '/images/devices/vaporesso-xros-3.png',
        category: 'Pod Systems',
        description: 'Adjustable airflow, 1000mAh battery, and ultra-slim design. Available in 8 colors.',
        stock_qty: 75,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'SMOK Nord 4 Kit',
        brand: 'SMOK',
        flavor: 'N/A (Hardware)',
        nicotine: 'N/A',
        price: 44.99,
        rating: 4.6,
        reviews: 4890,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Pod Systems',
        description: 'Up to 80W output in a pod format. The Nord 4 handles both MTL and DTL vaping.',
        stock_qty: 50,
        is_express_delivery: 1,
        is_bestseller: 1,
        is_new_arrival: 0,
    },
    // --- ACCESSORIES ---
    {
        name: 'SMOK RPM Series Replacement Coils (5-pack)',
        brand: 'SMOK',
        flavor: 'N/A',
        nicotine: 'N/A',
        price: 18.99,
        rating: 4.7,
        reviews: 890,
        image: '/images/accessories/smok-rpm-coils.jpeg',
        category: 'Accessories',
        description: 'High-performance mesh coils designed for maximum flavor clarity and longevity. 3-day lifespan.',
        stock_qty: 500,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 0,
    },
    {
        name: 'Cotton Bacon Prime - Wicking Cotton',
        brand: 'Wick \'N\' Vape',
        flavor: 'N/A',
        nicotine: 'N/A',
        price: 9.99,
        rating: 4.9,
        reviews: 3200,
        image: '/images/accessories/cotton-bacon-prime.jpg',
        category: 'Accessories',
        description: 'The gold standard in wicking cotton. Zero break-in time, pure flavor from the first pull.',
        stock_qty: 400,
        is_express_delivery: 1,
        is_bestseller: 1,
        is_new_arrival: 0,
    },
    // --- GLASS ---
    {
        name: 'Cookies Premium Glass - Flame Beaker Bong',
        brand: 'Cookies',
        flavor: 'N/A',
        nicotine: 'N/A',
        price: 119.50,
        rating: 4.7,
        reviews: 945,
        image: '/images/cookies-flame-beaker.JPG',
        category: 'Glass',
        description: 'Authentic Cookies branded borosilicate glassware for the smoothest, purest hits.',
        stock_qty: 20,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 0,
    },
    {
        name: 'Tyson 2.0 Gravity Bong - Heavyweight Edition',
        brand: 'Tyson',
        flavor: 'N/A',
        nicotine: 'N/A',
        price: 499.00,
        rating: 4.9,
        reviews: 320,
        image: '/images/tyson-gravity-bong-2.0.jpeg',
        category: 'Glass',
        description: 'Premium kinetic motion gravity bong championed by Mike Tyson. For serious collectors only.',
        stock_qty: 8,
        is_express_delivery: 0,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Ash Catcher 14mm - Honeycomb Perc',
        brand: 'PureGlass',
        flavor: 'N/A',
        nicotine: 'N/A',
        price: 34.99,
        rating: 4.6,
        reviews: 512,
        image: '/images/glass/ash-catcher-14mm.jpeg',
        category: 'Glass',
        description: 'Keeps your bong clean while adding extra filtration. Honeycomb perc for ultra-smooth hits.',
        stock_qty: 35,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 0,
    },
    // --- DEVICES (Specialty) ---
    {
        name: 'Puffco Plus Wax Pen Vaporizer',
        brand: 'Puffco',
        flavor: 'N/A (Hardware)',
        nicotine: 'N/A',
        price: 99.00,
        rating: 4.8,
        reviews: 2890,
        image: '/images/devices/puffco-plus-pen.jpeg',
        category: 'Devices',
        description: 'The industry benchmark for concentrate pens. Ceramic bowl, 3 heat settings, dart tool built in.',
        stock_qty: 25,
        is_express_delivery: 1,
        is_bestseller: 1,
        is_new_arrival: 0,
    },
    {
        name: 'Puffco Pivot Portable Vaporizer',
        brand: 'Puffco',
        flavor: 'N/A (Hardware)',
        nicotine: 'N/A',
        price: 189.00,
        rating: 4.8,
        reviews: 3100,
        image: '/images/puffco-pivot-device.jpg',
        category: 'Devices',
        description: 'Sleek, pocket-friendly, and powerful flavor extraction. Pivot joint for versatile use.',
        stock_qty: 15,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    // --- ROLLING ---
    {
        name: 'Backwoods Cigars - Honey Berry (5-pack)',
        brand: 'Backwoods',
        flavor: 'Honey Berry',
        nicotine: 'Tobacco',
        price: 9.99,
        rating: 4.9,
        reviews: 1240,
        image: '/images/backwoods-honey-berry.jpg',
        category: 'Rolling',
        description: 'Authentic rustic smoking experience with a sweet honey berry wrapper.',
        stock_qty: 250,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Juul2 Starter Kit with Virginia Tobacco Pods',
        brand: 'JUUL',
        flavor: 'Virginia Tobacco',
        nicotine: '5%',
        price: 29.99,
        rating: 4.5,
        reviews: 1820,
        image: '/images/juul-virginia-tobacco-pods.jpg',
        category: 'Pod Systems',
        description: 'The classic pod system. Smooth Virginia tobacco for former smokers making the switch.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 1,
        is_new_arrival: 0,
    },
    {
        name: 'Vuse Alto Kit with Rich Tobacco Pods',
        brand: 'Vuse',
        flavor: 'Rich Tobacco',
        nicotine: '5%',
        price: 26.99,
        rating: 4.4,
        reviews: 2100,
        image: '/images/devices/vuse-alto-kit.jpg',
        category: 'Pod Systems',
        description: 'Premium prefilled pods with rich tobacco flavor. Magnetic pod insertion, long-lasting battery.',
        stock_qty: 95,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 0,
    },
    // --- NEW INVENTORY FROM WEBSITE OWNER ---
    // Geekbar Pulse X Disposables
    {
        name: 'Geekbar Pulse X - Blackberry B Burst',
        brand: 'Geekbar Pulse X',
        flavor: 'Blackberry B Burst',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 150,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Bold blackberry burst flavor with 25000 puffs in the iconic Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Blue Rancher',
        brand: 'Geekbar Pulse X',
        flavor: 'Blue Rancher',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 120,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Cool blue rancher candy flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Blue Razz Ice',
        brand: 'Geekbar Pulse X',
        flavor: 'Blue Razz Ice',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 180,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Icy blue raspberry flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Miami Mint',
        brand: 'Geekbar Pulse X',
        flavor: 'Miami Mint',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 200,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Fresh Miami mint flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Cool Mint',
        brand: 'Geekbar Pulse X',
        flavor: 'Cool Mint',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 220,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Cool mint flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Strawberry Kiwi Ice',
        brand: 'Geekbar Pulse X',
        flavor: 'Strawberry Kiwi Ice',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 160,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Icy strawberry kiwi flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Pink Berry Lemonade',
        brand: 'Geekbar Pulse X',
        flavor: 'Pink Berry Lemonade',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 140,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Pink berry lemonade flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Pair of Thieves',
        brand: 'Geekbar Pulse X',
        flavor: 'Pair of Thieves',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 130,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Pair of Thieves flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Strawberry B Burst',
        brand: 'Geekbar Pulse X',
        flavor: 'Strawberry B Burst',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 170,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Strawberry burst flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Sour Straws',
        brand: 'Geekbar Pulse X',
        flavor: 'Sour Straws',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 110,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Sour straws candy flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Sour Fcking Fab',
        brand: 'Geekbar Pulse X',
        flavor: 'Sour Fcking Fab',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 125,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Sour fab candy flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Raspberry Peach Lime',
        brand: 'Geekbar Pulse X',
        flavor: 'Raspberry Peach Lime',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 135,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Raspberry peach lime flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Orange Fcking Fab',
        brand: 'Geekbar Pulse X',
        flavor: 'Orange Fcking Fab',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 115,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Orange fab candy flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Raspberry Jam',
        brand: 'Geekbar Pulse X',
        flavor: 'Raspberry Jam',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 145,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Raspberry jam flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Geekbar Pulse X - Blueberry Jam',
        brand: 'Geekbar Pulse X',
        flavor: 'Blueberry Jam',
        nicotine: '5%',
        price: 24.90,
        rating: 4.6,
        reviews: 155,
        image: '/images/geek-bar-pulse-x-25000-clear.jpg',
        category: 'Disposables',
        description: 'Blueberry jam flavor with 25000 puffs in the Pulse X disposable.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    // Foger Pod Systems
    {
        name: 'Foger Pods - Sour Blue Dust',
        brand: 'Foger',
        flavor: 'Sour Blue Dust',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 90,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Sour blue dust flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Miami Mint',
        brand: 'Foger',
        flavor: 'Miami Mint',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 110,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Miami mint flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Blue Ranger Blowup',
        brand: 'Foger',
        flavor: 'Blue Ranger Blowup',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 85,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Blue ranger blowup flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - OMG Blow Pop',
        brand: 'Foger',
        flavor: 'OMG Blow Pop',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 95,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'OMG blow pop flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Watermelon Bubblegum',
        brand: 'Foger',
        flavor: 'Watermelon Bubblegum',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 105,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Watermelon bubblegum flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Frozen Lemon',
        brand: 'Foger',
        flavor: 'Frozen Lemon',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 100,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Frozen lemon flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Gummy Bear',
        brand: 'Foger',
        flavor: 'Gummy Bear',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 115,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Gummy bear flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - White Gummy',
        brand: 'Foger',
        flavor: 'White Gummy',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 120,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'White gummy flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Triple Berry',
        brand: 'Foger',
        flavor: 'Triple Berry',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 130,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Triple berry flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Cherry Bomb',
        brand: 'Foger',
        flavor: 'Cherry Bomb',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 125,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Cherry bomb flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Sour Apple Ice',
        brand: 'Foger',
        flavor: 'Sour Apple Ice',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 135,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Sour apple ice flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Watermelon Ice',
        brand: 'Foger',
        flavor: 'Watermelon Ice',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 140,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Watermelon ice flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Kiwi Dragon Berry',
        brand: 'Foger',
        flavor: 'Kiwi Dragon Berry',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 145,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Kiwi dragon berry flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Red Velvet Cupcake',
        brand: 'Foger',
        flavor: 'Red Velvet Cupcake',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 150,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Red velvet cupcake flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Pineapple Coconut',
        brand: 'Foger',
        flavor: 'Pineapple Coconut',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 155,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Pineapple coconut flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Blueberry Watermelon',
        brand: 'Foger',
        flavor: 'Blueberry Watermelon',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 160,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Blueberry watermelon flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Gum Mint',
        brand: 'Foger',
        flavor: 'Gum Mint',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 165,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Gum mint flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Foger Pods - Cool Mint',
        brand: 'Foger',
        flavor: 'Cool Mint',
        nicotine: '5%',
        price: 13.99,
        rating: 4.5,
        reviews: 170,
        image: '/images/devices/uwell-caliburn-g2.webp',
        category: 'Pod Systems',
        description: 'Cool mint flavor in Foger pod system.',
        stock_qty: 80,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    // Utbar Disposables
    {
        name: 'Utbar - Aloe Grape',
        brand: 'Utbar',
        flavor: 'Aloe Grape',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 85,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Aloe grape flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - Aloe Watermelon',
        brand: 'Utbar',
        flavor: 'Aloe Watermelon',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 90,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Aloe watermelon flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - Blue Red Ice',
        brand: 'Utbar',
        flavor: 'Blue Red Ice',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 95,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Blue red ice flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - Cool Mint',
        brand: 'Utbar',
        flavor: 'Cool Mint',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 100,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Cool mint flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - Miami Mint',
        brand: 'Utbar',
        flavor: 'Miami Mint',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 105,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Miami mint flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - Mango Strawberry',
        brand: 'Utbar',
        flavor: 'Mango Strawberry',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 110,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Mango strawberry flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - Root Vanilla Soda',
        brand: 'Utbar',
        flavor: 'Root Vanilla Soda',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 115,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Root vanilla soda flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - Pink Berry Lemonade',
        brand: 'Utbar',
        flavor: 'Pink Berry Lemonade',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 120,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Pink berry lemonade flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - White Peach Lemon Head',
        brand: 'Utbar',
        flavor: 'White Peach Lemon Head',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 125,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'White peach lemon head flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - Blue Razz Lemonade',
        brand: 'Utbar',
        flavor: 'Blue Razz Lemonade',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 130,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Blue razz lemonade flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - Wildberry Drop',
        brand: 'Utbar',
        flavor: 'Wildberry Drop',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 135,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Wildberry drop flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - Passion Kiwi Pineapple',
        brand: 'Utbar',
        flavor: 'Passion Kiwi Pineapple',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 140,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Passion kiwi pineapple flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - Banana Smoothie Strawberry',
        brand: 'Utbar',
        flavor: 'Banana Smoothie Strawberry',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 145,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Banana smoothie strawberry flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - Watermelon Blow Pop',
        brand: 'Utbar',
        flavor: 'Watermelon Blow Pop',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 150,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Watermelon blow pop flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Utbar - Blue Rancher Lemonade',
        brand: 'Utbar',
        flavor: 'Blue Rancher Lemonade',
        nicotine: '5%',
        price: 23.99,
        rating: 4.4,
        reviews: 155,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Blue rancher lemonade flavor in Utbar disposable.',
        stock_qty: 90,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    // Flum Mello Disposables
    {
        name: 'Flum Mello - Watermelon Icy',
        brand: 'Flum Mello',
        flavor: 'Watermelon Icy',
        nicotine: '5%',
        price: 22.99,
        rating: 4.3,
        reviews: 80,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Watermelon icy flavor in Flum Mello disposable.',
        stock_qty: 85,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Flum Mello - Sour Apple Icy',
        brand: 'Flum Mello',
        flavor: 'Sour Apple Icy',
        nicotine: '5%',
        price: 22.99,
        rating: 4.3,
        reviews: 85,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Sour apple icy flavor in Flum Mello disposable.',
        stock_qty: 85,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Flum Mello - Sour Mango Pineapple',
        brand: 'Flum Mello',
        flavor: 'Sour Mango Pineapple',
        nicotine: '5%',
        price: 22.99,
        rating: 4.3,
        reviews: 90,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Sour mango pineapple flavor in Flum Mello disposable.',
        stock_qty: 85,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Flum Mello - Straw Melon',
        brand: 'Flum Mello',
        flavor: 'Straw Melon',
        nicotine: '5%',
        price: 22.99,
        rating: 4.3,
        reviews: 95,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Straw melon flavor in Flum Mello disposable.',
        stock_qty: 85,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Flum Mello - Watermelon Peach Lime',
        brand: 'Flum Mello',
        flavor: 'Watermelon Peach Lime',
        nicotine: '5%',
        price: 22.99,
        rating: 4.3,
        reviews: 100,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Watermelon peach lime flavor in Flum Mello disposable.',
        stock_qty: 85,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Flum Mello - White Gummy',
        brand: 'Flum Mello',
        flavor: 'White Gummy',
        nicotine: '5%',
        price: 22.99,
        rating: 4.3,
        reviews: 105,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'White gummy flavor in Flum Mello disposable.',
        stock_qty: 85,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Flum Mello - Cool Mint',
        brand: 'Flum Mello',
        flavor: 'Cool Mint',
        nicotine: '5%',
        price: 22.99,
        rating: 4.3,
        reviews: 110,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Cool mint flavor in Flum Mello disposable.',
        stock_qty: 85,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Flum Mello - Miami Mint',
        brand: 'Flum Mello',
        flavor: 'Miami Mint',
        nicotine: '5%',
        price: 22.99,
        rating: 4.3,
        reviews: 115,
        image: '/images/devices/elf-bar-bc5000.png',
        category: 'Disposables',
        description: 'Miami mint flavor in Flum Mello disposable.',
        stock_qty: 85,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    // Hydroxie 7oh Nic Salts
    {
        name: 'Hydroxie 7oh - 10-15mg',
        brand: 'Hydroxie 7oh',
        flavor: 'N/A',
        nicotine: '10-15mg',
        price: 14.99,
        rating: 4.7,
        reviews: 200,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nic Salts',
        description: 'Hydroxie 7oh nicotine salt with 10-15mg nicotine strength.',
        stock_qty: 120,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Hydroxie 7oh - 10-30mg',
        brand: 'Hydroxie 7oh',
        flavor: 'N/A',
        nicotine: '10-30mg',
        price: 24.99,
        rating: 4.7,
        reviews: 210,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nic Salts',
        description: 'Hydroxie 7oh nicotine salt with 10-30mg nicotine strength.',
        stock_qty: 120,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Hydroxie 7oh - 5-15mg',
        brand: 'Hydroxie 7oh',
        flavor: 'N/A',
        nicotine: '5-15mg',
        price: 14.99,
        rating: 4.7,
        reviews: 220,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nic Salts',
        description: 'Hydroxie 7oh nicotine salt with 5-15mg nicotine strength.',
        stock_qty: 120,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Hydroxie 7oh - 5-30mg',
        brand: 'Hydroxie 7oh',
        flavor: 'N/A',
        nicotine: '5-30mg',
        price: 24.99,
        rating: 4.7,
        reviews: 230,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nic Salts',
        description: 'Hydroxie 7oh nicotine salt with 5-30mg nicotine strength.',
        stock_qty: 120,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Hydroxie 7oh - 5-60mg',
        brand: 'Hydroxie 7oh',
        flavor: 'N/A',
        nicotine: '5-60mg',
        price: 39.99,
        rating: 4.7,
        reviews: 240,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nic Salts',
        description: 'Hydroxie 7oh nicotine salt with 5-60mg nicotine strength.',
        stock_qty: 120,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    // Blues Nic Salts
    {
        name: 'Blues - 35mg',
        brand: 'Blues',
        flavor: 'N/A',
        nicotine: '35mg',
        price: 12,
        rating: 4.6,
        reviews: 180,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nic Salts',
        description: 'Blues nicotine salt with 35mg nicotine strength.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Blues - 55mg',
        brand: 'Blues',
        flavor: 'N/A',
        nicotine: '55mg',
        price: 18,
        rating: 4.6,
        reviews: 190,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nic Salts',
        description: 'Blues nicotine salt with 55mg nicotine strength.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Blues - 75mg',
        brand: 'Blues',
        flavor: 'N/A',
        nicotine: '75mg',
        price: 22,
        rating: 4.6,
        reviews: 200,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nic Salts',
        description: 'Blues nicotine salt with 75mg nicotine strength.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Blues - 100mg',
        brand: 'Blues',
        flavor: 'N/A',
        nicotine: '100mg',
        price: 25,
        rating: 4.6,
        reviews: 210,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nic Salts',
        description: 'Blues nicotine salt with 100mg nicotine strength.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Blues - 120mg',
        brand: 'Blues',
        flavor: 'N/A',
        nicotine: '120mg',
        price: 25,
        rating: 4.6,
        reviews: 220,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nic Salts',
        description: 'Blues nicotine salt with 120mg nicotine strength.',
        stock_qty: 100,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    // Zyns Nicotine Pouches
    {
        name: 'Zyns - Wintergreen 6mg',
        brand: 'Zyns',
        flavor: 'Wintergreen',
        nicotine: '6mg',
        price: 5.99,
        rating: 4.8,
        reviews: 500,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nicotine Pouches',
        description: 'Zyns nicotine pouch with wintergreen flavor and 6mg nicotine.',
        stock_qty: 200,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Zyns - Peppermint 6mg',
        brand: 'Zyns',
        flavor: 'Peppermint',
        nicotine: '6mg',
        price: 5.99,
        rating: 4.8,
        reviews: 520,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nicotine Pouches',
        description: 'Zyns nicotine pouch with peppermint flavor and 6mg nicotine.',
        stock_qty: 200,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Zyns - Citrus 6mg',
        brand: 'Zyns',
        flavor: 'Citrus',
        nicotine: '6mg',
        price: 5.99,
        rating: 4.8,
        reviews: 540,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nicotine Pouches',
        description: 'Zyns nicotine pouch with citrus flavor and 6mg nicotine.',
        stock_qty: 200,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Zyns - Cool Mint 6mg',
        brand: 'Zyns',
        flavor: 'Cool Mint',
        nicotine: '6mg',
        price: 5.99,
        rating: 4.8,
        reviews: 560,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nicotine Pouches',
        description: 'Zyns nicotine pouch with cool mint flavor and 6mg nicotine.',
        stock_qty: 200,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
    {
        name: 'Zyns - Cinnamon 6mg',
        brand: 'Zyns',
        flavor: 'Cinnamon',
        nicotine: '6mg',
        price: 5.99,
        rating: 4.8,
        reviews: 580,
        image: '/images/devices/smok-nord-4-kit.jpg',
        category: 'Nicotine Pouches',
        description: 'Zyns nicotine pouch with cinnamon flavor and 6mg nicotine.',
        stock_qty: 200,
        is_express_delivery: 1,
        is_bestseller: 0,
        is_new_arrival: 1,
    },
];

export function seed() {
    const db = getDb();

    const count = (db.prepare('SELECT COUNT(*) as cnt FROM products').get() as { cnt: number }).cnt;
    const forceReseed = process.env.FORCE_RESEED === 'true';

    if (!forceReseed && count > 0) {
        console.log(`[Seed] DB already has ${count} products — skipping seed.`);
        return;
    }

    if (count > 0) {
        console.log('[Seed] Clearing products table for reseed...');
        db.prepare('DELETE FROM products').run();
    }

    const insert = db.prepare(`
    INSERT INTO products
      (name, brand, flavor, nicotine, price, rating, reviews, image, category, description,
       stock_qty, is_express_delivery, is_bestseller, is_new_arrival)
    VALUES
      (@name, @brand, @flavor, @nicotine, @price, @rating, @reviews, @image, @category, @description,
       @stock_qty, @is_express_delivery, @is_bestseller, @is_new_arrival)
  `);

    const seedAll = db.transaction(() => {
        for (const p of products) {
            insert.run(p);
        }
    });

    seedAll();
    console.log(`[Seed] Seeded ${products.length} products into the DB${forceReseed ? ' (force reseed)' : ''}.`);
}
