import getDb from './index.js';

const products = [
  // --- MODS ---
  {
    name: 'VaporMax Elite Pro Mod - Carbon Fiber Edition',
    brand: 'TitanVape',
    flavor: 'N/A (Hardware)',
    nicotine: 'N/A',
    price: 149.99,
    rating: 4.9,
    reviews: 2450,
    image: '/images/devices/geekvape-aegis-legend.jpg',
    category: 'Mods',
    description: 'The ultimate power for professional vapers. Dual-21700 battery configuration and the advanced Titan-X chipset with OLED display.',
    stock_qty: 45,
    is_express_delivery: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
  },
  {
    name: 'GeekVape Aegis Legend 2 200W',
    brand: 'GeekVape',
    flavor: 'N/A (Hardware)',
    nicotine: 'N/A',
    price: 79.99,
    rating: 4.8,
    reviews: 3820,
    image: '/images/devices/geekvape-aegis-legend.jpg',
    category: 'Mods',
    description: 'IP68 waterproof, dustproof, and shockproof. The most rugged mod for everyday carry.',
    stock_qty: 30,
    is_express_delivery: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
  },
  // --- DISPOSABLES ---
  {
    name: 'Geek Bar Pulse X 25000 Puffs - Clear',
    brand: 'Geek Bar',
    flavor: 'Clear',
    nicotine: '5%',
    price: 24.50,
    rating: 4.6,
    reviews: 5102,
    image: '/images/geek-bar-pulse-x-25000-clear.jpg',
    category: 'Disposables',
    description: 'The longest lasting disposable with a built-in LED screen for e-liquid and battery monitoring.',
    stock_qty: 200,
    is_express_delivery: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
  },
  {
    name: 'Elf Bar BC5000 - Strawberry Mango',
    brand: 'Elf Bar',
    flavor: 'Strawberry Mango',
    nicotine: '5%',
    price: 18.99,
    rating: 4.7,
    reviews: 8930,
    image: '/images/devices/elf-bar-bc5000.png',
    category: 'Disposables',
    description: 'The classic Elf Bar with a tropical twist — 5000 puffs, rechargeable, and iconic flavor.',
    stock_qty: 300,
    is_express_delivery: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
  },
  {
    name: 'Lost Mary OS5000 - Blue Cotton Candy',
    brand: 'Lost Mary',
    flavor: 'Blue Cotton Candy',
    nicotine: '5%',
    price: 19.99,
    rating: 4.8,
    reviews: 4215,
    image: '/images/devices/elf-bar-bc5000.png',
    category: 'Disposables',
    description: 'Sweet, airy cotton candy clouds with a smooth 5% nicotine hit. 5000 puffs guaranteed.',
    stock_qty: 150,
    is_express_delivery: 1,
    is_bestseller: 0,
    is_new_arrival: 1,
  },
  // --- E-LIQUIDS ---
  {
    name: 'Arctic Breeze Menthol - Sub-Ohm 60ml',
    brand: 'FrostBite',
    flavor: 'Pure Menthol & Peppermint',
    nicotine: '0mg, 3mg, 6mg',
    price: 19.50,
    rating: 4.7,
    reviews: 945,
    image: '/images/devices/smok-nord-4-kit.jpg',
    category: 'E-Liquids',
    description: 'The cleanest, coldest menthol on the market. Perfect for cloud chasing.',
    stock_qty: 80,
    is_express_delivery: 1,
    is_bestseller: 0,
    is_new_arrival: 0,
  },
  {
    name: 'Strawberry Dream Salt Nic - Premium Series 30ml',
    brand: 'SweetCloud',
    flavor: 'Strawberry Cream & Custard',
    nicotine: '25mg, 50mg',
    price: 22.99,
    rating: 4.5,
    reviews: 1820,
    image: '/images/devices/smok-nord-4-kit.jpg',
    category: 'Nic Salts',
    description: 'A smooth, creamy strawberry experience perfectly balanced for high-nicotine pod systems.',
    stock_qty: 120,
    is_express_delivery: 1,
    is_bestseller: 0,
    is_new_arrival: 0,
  },
  {
    name: 'Mango Tango Tropical Blend 100ml',
    brand: 'Tropika Vapes',
    flavor: 'Mango, Pineapple & Passionfruit',
    nicotine: '0mg, 3mg',
    price: 27.99,
    rating: 4.6,
    reviews: 2310,
    image: '/images/devices/smok-nord-4-kit.jpg',
    category: 'E-Liquids',
    description: 'A vacation in a bottle. Pure tropical escape with sweet mango and tangy pineapple.',
    stock_qty: 90,
    is_express_delivery: 0,
    is_bestseller: 0,
    is_new_arrival: 1,
  },
  // --- POD SYSTEMS ---
  {
    name: 'Uwell Caliburn G2 Pod System',
    brand: 'Uwell',
    flavor: 'N/A (Hardware)',
    nicotine: 'N/A',
    price: 39.99,
    rating: 4.9,
    reviews: 6750,
    image: '/images/devices/uwell-caliburn-g2.webp',
    category: 'Pod Systems',
    description: 'Industry-leading flavor in a slim, pocket-friendly design. The G2 sets the standard.',
    stock_qty: 60,
    is_express_delivery: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
  },
  {
    name: 'Vaporesso XROS 3 Mini',
    brand: 'Vaporesso',
    flavor: 'N/A (Hardware)',
    nicotine: 'N/A',
    price: 34.99,
    rating: 4.7,
    reviews: 3100,
    image: '/images/devices/vaporesso-xros-3.png',
    category: 'Pod Systems',
    description: 'Adjustable airflow, 1000mAh battery, and ultra-slim design. Available in 8 colors.',
    stock_qty: 75,
    is_express_delivery: 1,
    is_bestseller: 0,
    is_new_arrival: 1,
  },
  {
    name: 'SMOK Nord 4 Kit',
    brand: 'SMOK',
    flavor: 'N/A (Hardware)',
    nicotine: 'N/A',
    price: 44.99,
    rating: 4.6,
    reviews: 4890,
    image: '/images/devices/smok-nord-4-kit.jpg',
    category: 'Pod Systems',
    description: 'Up to 80W output in a pod format. The Nord 4 handles both MTL and DTL vaping.',
    stock_qty: 50,
    is_express_delivery: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
  },
  // --- ACCESSORIES ---
  {
    name: 'SMOK RPM Series Replacement Coils (5-pack)',
    brand: 'SMOK',
    flavor: 'N/A',
    nicotine: 'N/A',
    price: 18.99,
    rating: 4.7,
    reviews: 890,
    image: '/images/accessories/smok-rpm-coils.jpeg',
    category: 'Accessories',
    description: 'High-performance mesh coils designed for maximum flavor clarity and longevity. 3-day lifespan.',
    stock_qty: 500,
    is_express_delivery: 1,
    is_bestseller: 0,
    is_new_arrival: 0,
  },
  {
    name: 'Cotton Bacon Prime - Wicking Cotton',
    brand: 'Wick \'N\' Vape',
    flavor: 'N/A',
    nicotine: 'N/A',
    price: 9.99,
    rating: 4.9,
    reviews: 3200,
    image: '/images/accessories/cotton-bacon-prime.jpg',
    category: 'Accessories',
    description: 'The gold standard in wicking cotton. Zero break-in time, pure flavor from the first pull.',
    stock_qty: 400,
    is_express_delivery: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
  },
  // --- GLASS ---
  {
    name: 'Cookies Premium Glass - Flame Beaker Bong',
    brand: 'Cookies',
    flavor: 'N/A',
    nicotine: 'N/A',
    price: 119.50,
    rating: 4.7,
    reviews: 945,
    image: '/images/cookies-flame-beaker.JPG',
    category: 'Glass',
    description: 'Authentic Cookies branded borosilicate glassware for the smoothest, purest hits.',
    stock_qty: 20,
    is_express_delivery: 1,
    is_bestseller: 0,
    is_new_arrival: 0,
  },
  {
    name: 'Tyson 2.0 Gravity Bong - Heavyweight Edition',
    brand: 'Tyson',
    flavor: 'N/A',
    nicotine: 'N/A',
    price: 499.00,
    rating: 4.9,
    reviews: 320,
    image: '/images/tyson-gravity-bong-2.0.jpeg',
    category: 'Glass',
    description: 'Premium kinetic motion gravity bong championed by Mike Tyson. For serious collectors only.',
    stock_qty: 8,
    is_express_delivery: 0,
    is_bestseller: 0,
    is_new_arrival: 1,
  },
  {
    name: 'Ash Catcher 14mm - Honeycomb Perc',
    brand: 'PureGlass',
    flavor: 'N/A',
    nicotine: 'N/A',
    price: 34.99,
    rating: 4.6,
    reviews: 512,
    image: '/images/glass/ash-catcher-14mm.jpeg',
    category: 'Glass',
    description: 'Keeps your bong clean while adding extra filtration. Honeycomb perc for ultra-smooth hits.',
    stock_qty: 35,
    is_express_delivery: 1,
    is_bestseller: 0,
    is_new_arrival: 0,
  },
  // --- DEVICES (Specialty) ---
  {
    name: 'Puffco Plus Wax Pen Vaporizer',
    brand: 'Puffco',
    flavor: 'N/A (Hardware)',
    nicotine: 'N/A',
    price: 99.00,
    rating: 4.8,
    reviews: 2890,
    image: '/images/devices/puffco-plus-pen.jpeg',
    category: 'Devices',
    description: 'The industry benchmark for concentrate pens. Ceramic bowl, 3 heat settings, dart tool built in.',
    stock_qty: 25,
    is_express_delivery: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
  },
  {
    name: 'Puffco Pivot Portable Vaporizer',
    brand: 'Puffco',
    flavor: 'N/A (Hardware)',
    nicotine: 'N/A',
    price: 189.00,
    rating: 4.8,
    reviews: 3100,
    image: '/images/puffco-pivot-device.jpg',
    category: 'Devices',
    description: 'Sleek, pocket-friendly, and powerful flavor extraction. Pivot joint for versatile use.',
    stock_qty: 15,
    is_express_delivery: 1,
    is_bestseller: 0,
    is_new_arrival: 1,
  },
  // --- ROLLING ---
  {
    name: 'Backwoods Cigars - Honey Berry (5-pack)',
    brand: 'Backwoods',
    flavor: 'Honey Berry',
    nicotine: 'Tobacco',
    price: 9.99,
    rating: 4.9,
    reviews: 1240,
    image: '/images/backwoods-honey-berry.jpg',
    category: 'Rolling',
    description: 'Authentic rustic smoking experience with a sweet honey berry wrapper.',
    stock_qty: 250,
    is_express_delivery: 1,
    is_bestseller: 0,
    is_new_arrival: 1,
  },
  {
    name: 'Juul2 Starter Kit with Virginia Tobacco Pods',
    brand: 'JUUL',
    flavor: 'Virginia Tobacco',
    nicotine: '5%',
    price: 29.99,
    rating: 4.5,
    reviews: 1820,
    image: '/images/juul-virginia-tobacco-pods.jpg',
    category: 'Pod Systems',
    description: 'The classic pod system. Smooth Virginia tobacco for former smokers making the switch.',
    stock_qty: 80,
    is_express_delivery: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
  },
  {
    name: 'Vuse Alto Kit with Rich Tobacco Pods',
    brand: 'Vuse',
    flavor: 'Rich Tobacco',
    nicotine: '5%',
    price: 26.99,
    rating: 4.4,
    reviews: 2100,
    image: '/images/devices/vuse-alto-kit.jpg',
    category: 'Pod Systems',
    description: 'Premium prefilled pods with rich tobacco flavor. Magnetic pod insertion, long-lasting battery.',
    stock_qty: 95,
    is_express_delivery: 1,
    is_bestseller: 0,
    is_new_arrival: 0,
  },
];

export function seed() {
  const db = getDb();

  const count = (db.prepare('SELECT COUNT(*) as cnt FROM products').get() as { cnt: number }).cnt;
  if (count > 0) {
    console.log(`[Seed] DB already has ${count} products — skipping seed.`);
    return;
  }

  const insert = db.prepare(`
    INSERT INTO products 
      (name, brand, flavor, nicotine, price, rating, reviews, image, category, description,
       stock_qty, is_express_delivery, is_bestseller, is_new_arrival)
    VALUES 
      (@name, @brand, @flavor, @nicotine, @price, @rating, @reviews, @image, @category, @description,
       @stock_qty, @is_express_delivery, @is_bestseller, @is_new_arrival)
  `);

  const seedAll = db.transaction(() => {
    for (const p of products) {
      insert.run(p);
    }
  });

  seedAll();
  console.log(`[Seed] Seeded ${products.length} products into the DB.`);
}
